### ISSUE TITLE
[Bug]: Always-run attestor type duplication

### ISSUE THREAD

**Issue by Strakeln** [in-toto/witness#374] opened 2024-01-29 19:17 UTC
**What steps did you take and what happened:**

If a user specifies one of the always-run attestor types (`product` and `material`), the specified attestor type is run twice.

Example:

`witness run -a product -s test -k key.pem -o output.json --echo "hello" >test.txt`

> INFO    Starting material attestor...                
> INFO    Starting command-run attestor...             
> INFO    Starting product attestor...                 
> INFO    Starting product attestor...    

Note the duplicate "starting product attestor" statement. In the resulting attestation, there are two `product` attestors. Same behavior applies if you specify the `material` attestor.

**What did you expect to happen:**

> INFO    Starting material attestor...                
> INFO    Starting command-run attestor...             
> INFO    Starting product attestor...       

(and the resulting output attestation to only have one product attestation)

**Environment:**

- Witness version: 0.1.14 and 0.2.0
- Architecture: Linux amd64
- Attestors used: product, material

**Comment by ChaosInTheCRD** [comment] 2024-01-29 19:35
Hi @Strakeln 👋 

So this is actually an issue that has been folded out, but it hasn't yet made its way out in the form of a release. You can see the fix [here](https://github.com/in-toto/witness/commit/06031da4459ee4aea13ee83c59f9dee8171133ff). If you'd like, you can also validate that the problem is gone by running `go run . run ...` in the project directory if you have it cloned 😄.

Hopefull that answers your question, and if you want to know anything else please feel free to update this issue. Also pleae let me know if you are happy for me to close the issue (might be worth waiting if you want to run the `main` branch code locally).

**Comment by Strakeln** [comment] 2024-01-29 20:47
Excellent news, @ChaosInTheCRD - thanks for the update. I am good with you closing the issue. Thanks!

**Closed as completed** 2024-01-30 10:50 UTC
Labels: bug
